version: '3.8'

services:
  laravel:
      build:
        context: ../../
        dockerfile: ./docker/php/Dockerfile
        target: ecr
      image: ${IMAGE_NAME}
      environment:
        TEST: "Asia/Tokyo"
      container_name: laravel
      ports:
        - 8080:80