version: '3.8'

services:
  laravel:
      build:
        context: ../../
        dockerfile: ./docker/php/Dockerfile
        target: local
      image: laravel/php-apache
      container_name: laravel
      ports:
        - 8080:80
      volumes:
        - ../../src:/var/www/laravel